# docker/Dockerfile.backend

FROM python:3.10

# Crear directorio de trabajo
WORKDIR /app

# Copiar requirements y luego instalar dependencias
COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo el proyecto, incluyendo /backend y main.py
COPY . .

# Exponer el puerto
EXPOSE 8000

# Comando para ejecutar FastAPI
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]