# docker/Dockerfile.rasa

FROM rasa/rasa:3.6.10

WORKDIR /app

# Copiar el contenido de la carpeta rasa
COPY rasa/ .

# Entrenar el modelo
RUN rasa train

# Exponer puerto y ejecutar Rasa
CMD ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]
