FROM rasa/rasa:3.6.10

WORKDIR /app

# Copiar toda la carpeta rasa
COPY rasa/ .

# Entrenar el modelo
RUN rasa train

# Exponer puerto y ejecutar Rasa
CMD ["rasa", "run", "--enable-api", "--cors", "*", "--debug"]

