version: "3.1"

language: "es"

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer

  # Extrae la entidad "email" desde el regex del nlu.yml
  - name: RegexEntityExtractor
    case_sensitive: false
    use_lookup_tables: true
    use_regexes: true
    use_word_boundaries: true

  - name: LexicalSyntacticFeaturizer

  # Mejora comprensión en ES con n-gramas de caracteres
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true

  - name: EntitySynonymMapper

  - name: ResponseSelector
    epochs: 100
    constrain_similarities: true

  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

policies:
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: true

  - name: MemoizationPolicy
    max_history: 5

  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true