name: Train Rasa on Push

on:
  push:
    paths:
      - 'rasa/**'
      - '.github/workflows/train_rasa.yml'

jobs:
  train_rasa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Rasa
        run: |
          pip install rasa

      - name: Train the model
        run: |
          cd rasa
          rasa train